### PR TITLE
Heatmap worker fix

### PR DESCRIPTION
**Pull request by dgrechka**
1. Now the release does not contain **idd.heatmapworker.js** as well as **idd.transforms.js** needed by the worker. This disables the heatmap chart feature in case of using the IDD release via bower.
This pull request adds copying web worker related files to the build output dir.

2. Currently the path where the web worker code is loaded from is hardcoded to **"script/"** folder.
This pull request adds **InteractiveDataDisplay.SetWebWorkersPath** to override the default location in case of the user has another directory layout.

Please create minor release to enable heatmap charts in bower-package installations

### CODE REVIEW

**Comment by sergey-berezin** [comment]
I suggest to embed worker script into main script like this:

```
// String with base64 script. In real scenario base64 string will be generated by build process from external file
var workerScriptB64 = window.btoa('onmessage = function(m) { postMessage("Hello, " + m.data + "!"); }'); 

var workerBlob = new Blob([ window.atob(workerScriptB64) ], { type: 'text/javascript' });
var worker = new Worker(window.URL.createObjectURL(workerBlob));
worker.onmessage = function(m) { window.alert(m.data); }
worker.postMessage("World");
```

**Comment by dvoits** [comment]
Just curious, why there are two operations: first, 'btoa', then 'atob' of the same text?

**Comment by sergey-berezin** [comment]
workerScriptB64 is base64 encoded script file. To avoid escaping/unescaping.

So last four lines of code is what should really work in IDD.

Instead of first line we'll use build process.

**Comment by dgrechka** [comment]
Updated the branch. Please, review.

The WebWorker is loaded from blob. base64 representation is prepared during the build and included to idd.js during concatenation. No web worker source file is now required.

Temporary disabled 3 heatmap tests as PhantomJS does not support blobs and can't load the worker code from blob.

**Comment by dgrechka** [comment]
Updated source branch.Now the tests are not disabled.
Running Jasmine tests in a browser rather than in PhantomJS to load web worker from the blob.

**Comment by sergey-berezin** [comment]
I implemented alternative solution - detect PhantomJS in code and load heatmap web worker script in usual manner. Pro: grunt run require no user intervention (hitting Ctrl+C, closing browser). Anyway, thank you for pointing to 'connect' plugin!

**Pull request closed without merging**
